"""empty message

Revision ID: 187ecf6e65cc
Revises: 9a471b357e15
Create Date: 2022-08-07 14:11:47.612745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187ecf6e65cc'
down_revision = '9a471b357e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement_units', 'system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_units', sa.Column('system', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
