"""empty message

Revision ID: 9a471b357e15
Revises: 6a6f1e57fc08
Create Date: 2022-08-02 14:00:39.460674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a471b357e15'
down_revision = '6a6f1e57fc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_units', sa.Column('unit', sa.String(length=50), nullable=False))
    op.add_column('measurement_units', sa.Column('system', sa.String(length=50), nullable=False))
    op.drop_column('measurement_units', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement_units', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('measurement_units', 'unit')
    op.drop_column('measurement_units', 'system')
    # ### end Alembic commands ###
